### ISSUE TITLE
Quantumult X支持

### ISSUE THREAD

**Issue by vpromise** [suiyuran/stash#1]
非常实用，不知道作者能否提供Quantumult X的支持，十分感谢

**Comment by suiyuran** [comment]
我没有 Quantumult X，也没找到官方文档。

**Comment by vpromise** [comment]
非常感谢作者提供的思路，在热心网友帮助下已实现Quantumult X的支持，参见[V2EX](https://www.v2ex.com/t/995504#reply17)。
